### ISSUE TITLE
[RFC] API redesign

### ISSUE THREAD

**Issue by FFY00** [ocaballeror/jeepney-objects#2]
The current implementation is a good starting point but just a PoC in my opinion, it should not be the final API.

Requirements:
  - Support the `SESSION` and `SYSTEM` buses
  - Modularity: ability to register different objects to different paths
    - The connection would be separated from the objects, this way we can support all integration types, not just `blocking`
    - Support for nested objects
  - Re-use the objects in the client
  - Easy to use
    - Get signatures via the python type system or DBus introspection file (not sure)
  - Support at least Peer and Properties (including PropertiesChanged)
    - Over time we also want to support Introspectable and ObjectManager

Good to have:
  - Auto-generate an introspection file (this will kind of be required when adding support for the Introspectable interface)
    - Bonus points if we can generate documentation

@ocaballeror, what do you think? Do you think it makes sense to do this here, or I am better off doing it in my own project? Let me know.

**Comment by ocaballeror** [comment]
You are right, this is very much a PoC. Actually, the only reason I created this was because I needed some way to test the DBus integration for one of my other projects. I stumbled into jeepney and implemented the bare minimum to be able to have an object with properties and methods and then use that in my test suite.

What you're talking about is a full fledged DBus library. Honestly, I like the idea, but given that it doesn't have much of a use for me, I don't know how far into the future would I get before I got bored of it and stopped really doing anything. Also, given that my knowledge of dbus is very limited, I'm afraid I would be more of a burden than an aid.

If you want to, by all means start your own project and implement all those features. You can use however much or little from my code as you wish and I don't even really care much if you quote me or not. Again, this was just a poc, so I wouldn't feel personally stolen from if you just copied and pasted this and called it your own.

All of that being said, if you want or need my help during the initial stages I will be happy to do so. It's been a while since I've worked on something moderately big, so I would gladly help a fellow archlinuxer as long as I can/feel like it.

PS: If you've gotten to this stage, I assume you've already looked at the other python dbus implementations, but maybe take a moment to check out txdbus. It's pure python too, and although it depends very heavily on Twisted, it looks more mature than jeepney and it may have some of the things you need.

**Comment by FFY00** [comment]
Okay, I understand. I will do some experiments and see how viable my ideas are.

If everything turns out okay and I end up with something that works, do you mind if I steal the namespace?

Yes, I had a look a txdbus. My main two criteria for choosing a dependency for my project are, how good is the code quality? And, is the upstream active? Jeepney wins in both. I don't mind it being experimental as I am not afraid of getting my hands dirty. The state of DBus libraries in python seems a bit poor, with most of them being abandoned or deprecated. Jeepney is the most promising one, for multiple reasons, and for me it makes more sense to work on it and help it get to a state it can replace all other implementations.

**Comment by ocaballeror** [comment]
Absolutely, it's all yours.
I honestly just went for Jeepney because it's pure python with no external libraries, and it seemed like the only good option for that. But it's definitely rougher than the other ones, you WILL have to get your hands dirty. 

Best of luck. 
27. Apr. 2020, 00:49 von notifications@github.com:

**Comment by FFY00** [comment]
I think we can close this in favor of https://github.com/FFY00/dbus-objects. This module still is very useful as is, although not optimal. That is the issue I try to address in my project.

**Comment by ocaballeror** [comment]
@FFY00 yes, I looked at your implementation and it looks much more complete and feature-rich, and probably also easier to use and understand for new users. I'm still keeping this project alive, though, because I'm using it for some personal stuff, but I think most people looking for anything serious should go to your project instead.
